Refactor a bit

diff --git a/cleanrebase b/cleanrebase
--- a/cleanrebase
+++ b/cleanrebase
@@ -1,16 +1,18 @@
 #!/usr/bin/env sh
 set -e
 
-help="Usage: git checkout master && $0 <branch>
+help="Usage: git checkout master && ./cleanrebase [--help] <branch>
 
+Specify the <branch> you want to rebase onto master. Run the 'git rebase'
+command that this tools suggests, and follow the instructions given by git.
+Then run 'git checkout master && ./cleanrebase <branch>' again, until you
+see the message 'cleanrebase is DONE'.
+"
+help2="
 This tool suggests which rebase command to run next, for a rebase of <branch>
 onto master. It finds new commits on master that contain changes created by
 the 'cleanup' script, and makes sure the <branch> gets rebased on top of them
 with as little merge difficulties as possible.
-
-Run the suggested 'git rebase' command, and follow the instructions given by
-git. Then run 'git checkout master && $0 <branch>' again, until you see the
-message '$0 is DONE'.
 
 This is how the suggestions are made:
   * if the first new commit on master /does not/ contain changes created by
@@ -23,9 +25,9 @@ This is how the suggestions are made:
     'cleanup' script, then the suggested rebase command will move <branch> one
     commit closer to the tip of master. This is a special rebase command,
     which never results in a merge conflicts for you to solve (it favors the
-    commits from <branch> in case of a merge conflict, and runs the 'cleanup'
+    commits from <branch> in case of a merge conflict, runs the 'cleanup'
     script on all changed files (via an intermediate script called
-    'cleanupcommit', which also amends the final result)).
+    'cleanupcommit'), and then amends the changes to the commit).
 
 Your data should be safe when running the suggested commands. If you want, you
 can create backup snapshots of <branch> before you start, by running:
@@ -37,8 +39,9 @@ mailinglist or irc. Happy rebasing!
 "
 
 
+
 ### Functions
-die() { echo "Error in $0. $@" 1>&2; exit 1; }
+die() { echo "Error running cleanrebase. $@" 1>&2; exit 1; }
 
 version2int() {
   echo "$@" | awk '{print $NF}' | awk -F. '{printf "%03d%03d%03d", $1, $2, $3}'
@@ -54,10 +57,10 @@ fi
 for arg in "$@"; do
   case $arg in
     --help)
-      echo "$help"; exit 0
+      echo "$help$help2"; exit 0
       ;;
     *)
-      test -z "$branch" -a -n "$arg" || die "Usage: $0 [--help] <branch>"
+      test -z "$branch" -a -n "$arg" || die "Usage: ./cleanrebase [--help] <branch>"
       branch=$arg
       ;;
   esac
@@ -94,12 +97,12 @@ if [ -n "$cleanup_script_commit" ]; then
     command="git rebase $cleanup_script_commit^ $branch"
   else
     # -X theirs means keep code in $branch (confusingly)
-    command="git rebase -i -s recursive -X theirs --exec './cleanupcommit' $cleanup_script_commit $branch"
+    command="git rebase -i -X theirs -x './cleanupcommit && git commit -q -a --amend -C HEAD' $cleanup_script_commit $branch"
   fi
 elif [ -n "$first_new_commit" ]; then
   command="git rebase master $branch"
 else
-  echo "$0 is DONE" 1>&2; exit 1
+  echo "cleanrebase is DONE" 1>&2; exit 1
 fi
 
 echo $command
diff --git a/test b/test
--- a/test
+++ b/test
@@ -1,7 +1,7 @@
 #!/usr/bin/env sh
 set -e
 
-die() { echo "Error in $0. $@" 1>&2; exit 1; }
+die() { echo "Error. $@" 1>&2; exit 1; }
 
 assertOutput () {
   command="$1"
@@ -39,15 +39,15 @@ rm -rf testrepo
 mkdir testrepo
 cd testrepo
 git init -q
-cp ../cleanrebase ../cleanup ../cleanupcommit .
-git add cleanrebase cleanup cleanupcommit
+cp ../cleanrebase ../cleanup ../cleanupcommit ../cleanupindex .
+git add cleanrebase cleanup cleanupcommit cleanupindex
 echo 'two spaces-->  ' > spaces\ in\ filename
 echo 'two spaces-->  ' > 'newlines
 in
 filename'
 git add spaces* newlines*
 git commit -q -m 'initial commit'
-git submodule add ../testrepo testsubmodule # Can cause problems with ls-files
+git submodule -q add ../testrepo testsubmodule # Can cause problems with ls-files
 git commit -q -m 'second commit'
 
 # Run ui tests
@@ -55,18 +55,18 @@ shouldSucceed true
 shouldDieWith false ""
 git checkout -q -b temp &&
   shouldDieWith "./cleanrebase master" \
-  "Error in ./cleanrebase. Please run 'git checkout master' first" &&
+  "Error running cleanrebase. Please run 'git checkout master' first" &&
   git checkout -q master && git branch -q -D temp
 shouldDie "./cleanrebase" # Help text
 shouldSucceed "./cleanrebase --help" # Help text
 shouldDieWith "./cleanrebase one two" \
-  "Error in ./cleanrebase. Usage: ./cleanrebase [--help] <branch>"
+  "Error running cleanrebase. Usage: ./cleanrebase [--help] <branch>"
 shouldDieWith "./cleanrebase foo" \
-  "Error in ./cleanrebase. Branch 'foo' does not exist"
+  "Error running cleanrebase. Branch 'foo' does not exist"
 shouldDieWith "MINGIT=1.19.0 ./cleanrebase wip/test" \
-  "Error in ./cleanrebase. Please upgrade git to a version >= 1.19.0"
+  "Error running cleanrebase. Please upgrade git to a version >= 1.19.0"
 mkdir tmp && cd tmp && shouldDieWith "../cleanrebase wip/test" \
-  "Error in ../cleanrebase. File not found: 'cleanupcommit'. Are you in the repo root directory?" &&
+  "Error running cleanrebase. File not found: 'cleanupcommit'. Are you in the repo root directory?" &&
   cd ../ && rm -rf tmp
 
 # Add some test files and commits
@@ -87,22 +87,22 @@ git merge -q hs-bar -s ours -m 'conflict file.hs' # Branch wip/test wins.
 
 # Cleanup files on master
 git checkout -q master
-git ls-files -z | xargs -0 ./cleanup
+./cleanupindex
 git commit -a -m 'run cleanup script'
 
 # Some more commits on master
 sed -i 's/foo/bar/' file.lhs
 sed -i 's/$/  /' file.lhs # Make sure second cleanup has something to do.
 git commit -q -a -m "s/foo/bar/ file.lhs" # Introduce lhs-conflict.
-git ls-files -z | xargs -0 ./cleanup
+./cleanupindex
 git commit -a -m 'run cleanup script' # Test that cleanup commit can be last.
 
 # Rebase test branch onto master
 # 1
-`./cleanrebase wip/test`
+bash -c "`./cleanrebase wip/test`"
 # 2
 git checkout -q master
-`./cleanrebase wip/test` || true
+bash -c "`./cleanrebase wip/test`" || true
 assertOutput 'cat file.lhs | head -1' '<<<<<<< HEAD'
 assertOutput 'cat file.lhs | tail -1' '>>>>>>> s/foo/baz/'
 sed -i -n '/bar/p' file.lhs # solve conflict, master wins
@@ -110,10 +110,10 @@ git add file.lhs
 git rebase --continue
 # 3
 git checkout -q master
-`./cleanrebase wip/test`
+bash -c "`./cleanrebase wip/test`"
 # 4
 git checkout -q master
-shouldDieWith './cleanrebase wip/test' './cleanrebase is DONE'
+shouldDieWith './cleanrebase wip/test' 'cleanrebase is DONE'
 
 # Check final state
 # The idea of this test is that file.hs now contains 'baz', and file.lhs
